version: '3.8'

services:
  app:
    build:
      context: .
    container_name: fastapi_container
    ports:
      - "${FAST_APP_PORT}:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app
    networks:
      my_network:
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./local_db:/var/lib/postgresql/data:rw

networks:
  my_network:
