"""initial migration1

Revision ID: c6b436dbf6fe
Revises: 19a72d51af53
Create Date: 2024-09-25 18:35:13.873769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b436dbf6fe'
down_revision: Union[str, None] = '19a72d51af53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'creation_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'creation_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
